# Created with YamlCreate.ps1 v2.3.2 $debug=NVS1.CRLF.7-4-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Glarysoft.GlaryUtilities
PackageVersion: 6.7.0.10
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2024-03-04
Installers:
- Architecture: x86
  InstallerUrl: https://download.filepuma.com/files/system-utilities/glary-utilities/Glary_Utilities_v6.7.0.10.exe
  InstallerSha256: 6E25680148D5B13504B672471EA9364EC0B844ACCFF0546E9B001099F9BFC4B7
ManifestType: installer
ManifestVersion: 1.5.0
